name: meerkat_flutter
description: "CharML app creator adapter in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_js: ^0.8.0
  flutter_layout_grid: ^2.0.5
  html: ^0.15.4
  shake:
    git: 
      url: https://github.com/picolov/shake.git
      ref: master
  sqflite: ^2.3.2
  tabbed_view: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
